parameters:
#    admin_authors.example.class: FastForward\Bundle\Example

services:
#    admin_authors.example:
#        class: %admin_authors.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
